config/routes.rb
Rails.application.routes.draw do

  # admin
  namespace :admin do
    resource :application_settings, path: 'settings', only: [:show, :update]
    get 'users', to: 'dashboard#users'
    get 'projects', to: 'dashboard#projects'
    root to: 'dashboard#index'
  end

  # authentication
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/profile'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    patch 'users/:id/toggle_admin', to: 'users/profile#toggle_admin', as: :toggle_admin
    get 'users/:id', to: 'users/profile#show', as: :user
    get 'users/:id/edit', to: 'users/profile#edit', as: :edit_user
    get 'users/:id/activity', to: 'users/profile#activity', as: :user_activity
    get 'users/:id/projects', to: 'users/profile#projects', as: :user_projects
    patch 'users/:id', to: 'users/profile#update'
    get 'users/auth/:provider/setup', to: 'users/omniauth_callbacks#setup'
  end

  # resources
  resources :projects, except: :new do
    collection do
      get 'setup'
      post 'webhook'
    end
    member do
      get 'commits'
      get 'issues'
      get 'contributors'
    end
  end

  # root
  get '/pricing', to: 'root#pricing'
  get '/crash', to: 'root#crash'
  root to: 'root#index'
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end

  def pricing
  end

  def crash
    raise 'This error is for testing purposes'
  end
end

app/views/root/index.html.haml
.jumbotron
  %h1 Welcome to Appatite!
  %p
    This is the shiny, awesome way to view projects on Github and Gitlab.
  %p
    You just realized you need to put it on a dedicated screen near both developers
    and project managers.
  %p
    = link_to 'Get started', setup_projects_path, class: 'btn btn-primary btn-lg'

.container.text-center

  .about
    %h2 All projects, one view
    %p Get a quick overview of all your repositories in just a quick glance
    = image_tag 'screenshot_overview.png', class: 'img-thumbnail', width: 800

  .about
    %h2 Made for the wall
    %p All views are designed to be viewable on a screen attached to the wall
    = image_tag 'http://placehold.it/800x400', class: 'img-thumbnail', width: 800

  .about
    %h2 Don't forget mobile!
    %p Of course the dashboard fits perfectly on a small mobile screen, too
    = image_tag 'http://placehold.it/800x400', class: 'img-thumbnail', width: 800

app/views/root/pricing.haml
.text-center
  %h1 Choose your Appatite
  .lead
    A beautiful way to visualize your projects with a quick glance

.container
  .row
    .col-md-4.text-center
      .panel.panel-default.panel-featured
        .panel-heading
          Open Source
        .panel-body.text-center
          %h2.panel-headline Free
          Free forever for open source hobbyists
          .panel-action
            %a.btn.btn-md.btn-primary Get started
        %ul.list-group.text-left
          %li.list-group-item
            %span.fa.fa-check
            Up to 3 public repositories
          %li.list-group-item
            %span.fa.fa-check
            Both Github and Gitlab
          %li.list-group-item
            %span.fa.fa-check
            Something, something

    .col-md-4.text-center
      .panel.panel-success.panel-featured
        .panel-heading
          Standard
        .panel-body.text-center
          %h2.panel-headline
            %span.currency $
            1/mo
          Unlimited public repositories
          .panel-action
            %a.btn.btn-md.btn-success Buy Now
        %ul.list-group.text-left
          %li.list-group-item
            %span.fa.fa-check
            Unlimited public repositories
          %li.list-group-item
            %span.fa.fa-check
            Up to 3 private repositories
          %li.list-group-item
            %span.fa.fa-check
            Something, something

    .col-md-4.text-center
      .panel.panel-default.panel-featured
        .panel-heading
          Premium
        .panel-body.text-center
          %h2.panel-headline
            %span.currency $
            9/mo
          Unlimited private repositories
          .panel-action
            %a.btn.btn-md.btn-primary Buy Now
        %ul.list-group.text-left
          %li.list-group-item
            %span.fa.fa-check
            Unlimited private repositories
          %li.list-group-item
            %span.fa.fa-check
            Github Enterprise
          %li.list-group-item
            %span.fa.fa-check
            Gitlab CE and EE