config/routes.rb
Rails.application.routes.draw do

  # admin
  namespace :admin do
    resource :application_settings, path: 'settings', only: [:show, :update]
    get 'users', to: 'dashboard#users'
    get 'projects', to: 'dashboard#projects'
    root to: 'dashboard#index'
  end

  # authentication
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/profile'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    patch 'users/:id/toggle_admin', to: 'users/profile#toggle_admin', as: :toggle_admin
    get 'users/:id', to: 'users/profile#show', as: :user
    get 'users/:id/edit', to: 'users/profile#edit', as: :edit_user
    get 'users/:id/activity', to: 'users/profile#activity', as: :user_activity
    get 'users/:id/projects', to: 'users/profile#projects', as: :user_projects
    patch 'users/:id', to: 'users/profile#update'
    get 'users/auth/:provider/setup', to: 'users/omniauth_callbacks#setup'
  end

  # resources
  resources :projects, except: :new do
    collection do
      get 'setup'
      post 'webhook'
    end
    member do
      get 'commits'
      get 'issues'
      get 'contributors'
    end
  end

  # root
  get '/pricing', to: 'root#pricing'
  get '/crash', to: 'root#crash'
  root to: 'root#index'
end

app/controllers/admin/application_controller.rb
# Provides a base class for Admin controllers to subclass
#
# Automatically sets the layout and ensures an administrator is logged in
class Admin::ApplicationController < ApplicationController
  before_action :ensure_admin!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  after_action :set_csrf_cookie_for_ng
  before_action :set_raven_context

  # Ensure that AJAX requests carry the authenticity token
  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def render_403
    head :forbidden
  end

  def render_404
    render file: Rails.root.join('public', '404'), layout: false, status: '404'
  end

  def admin?
    User.count.zero? || (current_user&.admin?)
  end

  protected

  # Ensure that the user is signed in and admin
  def ensure_admin!
    respond_to do |format|
      format.html { render_404 }
      format.json { render json: { error: 'You need to be admin' }, status: :forbidden }
    end unless admin?
  end

  # Extend the CSRF verification to allow AJAX calls
  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

  private

  def set_raven_context
    return unless Rails.env.production?
    context = {}
    unless current_user.blank?
      context[:user_id] = current_user.id
      context[:email] = current_user.email
    end
    Raven.user_context(context)
    Raven.extra_context(params: params.to_hash, url: request.url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Check if a particular controller is the current one
  #
  # args - One or more controller names to check
  #
  # Examples
  #
  #   # On TreeController
  #   current_controller?(:tree)           # => true
  #   current_controller?(:commits)        # => false
  #   current_controller?(:commits, :tree) # => true
  def current_controller?(*args)
    args.any? do |v|
      v.to_s.downcase == controller.controller_name || v.to_s.downcase == controller.controller_path
    end
  end

  # Check if a particular action is the current one
  #
  # args - One or more action names to check
  #
  # Examples
  #
  #   # On Projects#new
  #   current_action?(:new)           # => true
  #   current_action?(:create)        # => false
  #   current_action?(:new, :create)  # => true
  def current_action?(*args)
    args.any? { |v| v.to_s.downcase == action_name }
  end

  # Check if the current visitor is an administrator.
  #
  # When no users are created, we allow any visitor to
  # access administrative controls.
  def admin?
    User.count.zero? || (current_user.present? && current_user.admin?)
  end
end

app/views/application/_analytics.haml
- if Rails.env.production? && ApplicationSetting.current.ga_tracking.present?
  %script
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', '#{ApplicationSetting.current.ga_tracking}', 'auto');
    - if user_signed_in?
      ga('set', 'userId', '#{current_user.email}');

app/views/application/_footer.haml
%footer.container.hidden-fullscreen
  %hr
  .row
    .col-md-5.text-left
      Copyright
    .col-md-2.text-center
      Logo
    .col-md-5.text-right
      Links
= render 'analytics'

app/views/application/_head.haml
%meta{ charset: 'utf-8' }
%meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
%meta{ name: :viewport, content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0' }
= favicon_link_tag 'favicon-tv.ico'
%title Appatite
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/application/_navbar.haml
%nav.navbar.navbar-default.navbar-appatite.hidden-fullscreen
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: 'collapse', target: "#navbar-collapse-1" } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to root_path, class: 'navbar-brand' do
        %span.fa.fa-tv
        Appatite

    .collapse.navbar-collapse#navbar-collapse-1
      %ul.nav.navbar-nav
        %li= link_to 'Projects', projects_path
        %li= link_to 'Pricing', pricing_path

      %ul.nav.navbar-nav.navbar-right
        %li.hidden-sm
          %a{ href: '#', ng: { click: 'goFullscreen()' } }
            %span.fa.fa-expand.fa-fw
        - if admin?
          %li
            = link_to admin_root_path do
              %span.hidden-xs
                %span.fa.fa-wrench.fa-fw
              %span.visible-xs
                Admin
        - if user_signed_in?
          %li.dropdown.dropdown-avatar
            %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' }, role: 'button', aria: { haspopup: true, expanded: false }}
              - if current_user.image.blank?
                %span.fa.fa-fw.fa-user
              - else
                = image_tag current_user.image, class: 'img-circle'
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to user_path(current_user) do
                  %span.fa.fa-user
                  Profile
              %li
                = link_to edit_user_path(current_user) do
                  %span.fa.fa-cog
                  Settings
              %li.divider{ role: 'separator' }
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %span.fa.fa-sign-out
                  Logout
        - elsif any_auth?
          %li
            = link_to new_user_session_path do
              %span.fa.fa-sign-in
              Login

app/views/application/_notifications.haml
- if notice
  .alert.alert-global.alert-success
    = notice

- if alert
  .alert.alert-global.alert-danger
    = alert