config/routes.rb
Rails.application.routes.draw do

  # admin
  namespace :admin do
    resource :application_settings, path: 'settings', only: [:show, :update]
    get 'users', to: 'dashboard#users'
    get 'projects', to: 'dashboard#projects'
    root to: 'dashboard#index'
  end

  # authentication
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/profile'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    patch 'users/:id/toggle_admin', to: 'users/profile#toggle_admin', as: :toggle_admin
    get 'users/:id', to: 'users/profile#show', as: :user
    get 'users/:id/edit', to: 'users/profile#edit', as: :edit_user
    get 'users/:id/activity', to: 'users/profile#activity', as: :user_activity
    get 'users/:id/projects', to: 'users/profile#projects', as: :user_projects
    patch 'users/:id', to: 'users/profile#update'
    get 'users/auth/:provider/setup', to: 'users/omniauth_callbacks#setup'
  end

  # resources
  resources :projects, except: :new do
    collection do
      get 'setup'
      post 'webhook'
    end
    member do
      get 'commits'
      get 'issues'
      get 'contributors'
    end
  end

  # root
  get '/pricing', to: 'root#pricing'
  get '/crash', to: 'root#crash'
  root to: 'root#index'
end

app/views/layouts/admin.html.haml
- content_for :content do
  .container{ ng: { controller: 'AdminCtrl' } }
    %ul.nav.nav-pills
      = nav_link(controller: :dashboard, action: :index) do
        = link_to 'Overview', admin_root_path
      = nav_link(controller: :dashboard, action: :users) do
        = link_to 'Users', admin_users_path
      = nav_link(controller: :dashboard, action: :projects) do
        = link_to 'Projects', admin_projects_path
      = nav_link(controller: :application_settings) do
        = link_to 'Settings', admin_application_settings_path
    = yield

= render template: 'layouts/application'

app/views/layouts/application.html.haml
%html
  %head
    = render 'head'
  %body{ ng: { controller: 'RootCtrl' } }
    = render 'navbar'
    = render 'notifications'
    = content_for?(:content) ? yield(:content) : yield
    = render 'footer'

app/views/layouts/profile.haml
- content_for :content do
  .container{ ng: { controller: 'ProfileCtrl' } }
    .row
      .col-md-3
        .text-center
          = avatar_for @user, size: '150'
          %h4= @user.name
          .lead= @user.nickname || 'Anonymous'
        .panel.panel-primary
          .panel-heading
            Basic info
          %ul.list-group
            %li.list-group-item
              %span.fa.fa-fw.fa-map-marker
              = @user.location.present? ? @user.location : 'All over the place'
            %li.list-group-item
              %span.fa.fa-fw.fa-calendar
              Joined #{time_ago_in_words @user.created_at} ago
            - if @user.website.present?
              %li.list-group-item
                %span.fa.fa-fw.fa-link
                = @user.website || 'No website'
          - if admin? or @user == current_user
            .panel-footer
              = link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-default'
      .col-md-9
        %ul.nav.nav-pills
          = nav_link(action: :show) do
            = link_to 'Overview', user_path(@user)
          = nav_link(action: :projects) do
            = link_to user_projects_path(@user) do
              Projects
              .badge= @user.following_projects_count
          = nav_link(action: :activity) do
            = link_to 'Activity', user_activity_path(@user)
        = yield

= render template: 'layouts/application'

app/views/layouts/profile.html.haml
- content_for :content do
  .container{ ng: { controller: 'ProfileCtrl' } }
    .row
      .col-md-3
        .text-center
          = avatar_for @user, size: '150'
          %h4= @user.name
          .lead= @user.nickname || 'Anonymous'
        .panel.panel-primary
          .panel-heading
            Basic info
          %ul.list-group
            %li.list-group-item
              %span.fa.fa-fw.fa-map-marker
              = @user.location.present? ? @user.location : 'All over the place'
            %li.list-group-item
              %span.fa.fa-fw.fa-calendar
              Joined #{time_ago_in_words @user.created_at} ago
            - if @user.website.present?
              %li.list-group-item
                %span.fa.fa-fw.fa-link
                = @user.website || 'No website'
          - if admin? or @user == current_user
            .panel-footer
              = link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-default'
      .col-md-9
        %ul.nav.nav-pills
          = nav_link(action: :show) do
            = link_to 'Overview', user_path(@user)
          = nav_link(action: :projects) do
            = link_to user_projects_path(@user) do
              Projects
              .badge= @user.following_projects_count
          = nav_link(action: :activity) do
            = link_to 'Activity', user_activity_path(@user)
        = yield

= render template: 'layouts/application'

app/views/layouts/projects.html.haml
- content_for :content do
  .container{ ng: { controller: 'ProjectCtrl', init: "load(#{@project.id})" } }

    .text-center.cover-block
      .cover-image
        %div{ ng: { hide: 'isRefreshing()' } }
          = content_tag :span, '', class: "fa fa-5x fa-#{@project.origin}"
        %div{ ng: { show: 'isRefreshing()' } }
          = content_tag :span, '', class: "fa fa-5x fa-spinner fa-pulse"
      %h2.cover-title{ ng: { bind: "project['name']" } }
      .cover-desc{ ng: { bind: "project['description']" } }

    %ul.nav.nav-pills.text-center
      = nav_link action: :show do
        = link_to 'Overview', project_path(@project)
      = nav_link action: :commits do
        = link_to 'Commits', commits_project_path(@project)
      = nav_link action: :issues do
        = link_to 'Issues', issues_project_path(@project)
      = nav_link action: :contributors do
        = link_to 'Contributors', contributors_project_path(@project)
      = nav_link action: :edit do
        = link_to 'Settings', edit_project_path(@project)

    = yield

= render template: 'layouts/application'